name: flake8 Lint

on:
   # Trigger the workflow on push or pull request,
   # but only for the main branch
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
  flake8-lint:

    runs-on: ubuntu-latest

    name: Lint

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      # Set up python version
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # check coding style
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with: 
          ignore: "E226,E501,F401,W503,W504"
          exclude: "./setup.py,./armageddon/__init__.py,./armageddon/test/test_armageddon.py"
